### PR TITLE
updated UI

### LINKED ISSUE #19: Update User Interface.
The user interface is garbage. It is upto your discretion to make it look better.

Some suggestions: (Not binding)
1. Change background
2. Incorporate a library similar to Bootstrap to make the User interface look better
3. Anything else that could make it look good

The bounty points you recieve will depend on the extent of imporvments you make!

### PR DESCRIPTION
**Pull request by sreechand2002**
**Brief Description of Fix**
BG changed and made the description text to align in the center and changed the button hover colors and added border to valied n type block
**Linked Issue**  
Closes #19

### CODE REVIEW

**Review by srujandeshpande — CHANGES_REQUESTED** [review]
Hey! Thanks for your effort.
I feel that the current combination of colors and background image is a better fit for this project though. I did like Description align in center and am willing to merge that if you undo the other changes/submit that one alone!

**Comment by sreechand2002** [comment]
can you elaborate what other changes i should undo?

**Comment by sreechand2002** [comment]
can you checkout this one

**Comment by sreechand2002** [comment]
can you merge it ?

**Comment by srujandeshpande** [comment]
Hey! The only change that will be merged is the formatting that you've done to the Luhn's algorithm paragraph. The changes to the colors and gradient are not needed

**Comment by srujandeshpande** [comment]
!bounty 20

**Comment by sreechand2002** [comment]
ok fine , i will update my PR

**Pull request merged**
