### PR TITLE
Theyashwanthsai luhnwiki patch 1

### LINKED ISSUE #56: Add a link to the Wikipedia for Luhn's Algorithm
### What do you want to see?

Add a link to the Wikipedia page for Luhn's algorithm on the page. The URL is https://en.wikipedia.org/wiki/Luhn_algorithm

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by theyashwanthsai**
**Brief Description of Fix**
Added the wiki link of Luhn algorithm
**Linked Issue**  
Closes #56 _ (Replace with Issue number)

### CODE REVIEW

**Comment by theyashwanthsai** [comment]
can someone tell me what happened?

**Comment by anirudhRowjee** [comment]
@theyashwanthsai do you still wish to have your changes merged into the codebase? If so, please reopen your PR.

**Comment by theyashwanthsai** [comment]
@anirudhRowjee  I am a fool. I will still be working on it.

**Comment by anirudhRowjee** [comment]
No worried @theyashwanthsai :sweat_smile: :smile: 
Let me know when you're ready to have me take a look at your PR.

**Comment by theyashwanthsai** [comment]
@anirudhRowjee i have reopened the PR. Please review it.....

**Comment by anirudhRowjee** [comment]
!bounty 25

**Pull request merged**
