### PR TITLE
closed head tag

### LINKED ISSUE #34: Missing <head> Closing tag
The </head> tag is incorrectly written as <head>

### PR DESCRIPTION
**Pull request by sreechand2002**
**Brief Description of Fix**
closed head tag
**Linked Issue**  
Closes #34

### CODE REVIEW

**Review by srujandeshpande — CHANGES_REQUESTED** [review]
The entire content is repeated twice.

**Comment by srujandeshpande** [comment]
All the content is repeated twice. Please check carefully before submitting a PR

**Comment by sreechand2002** [comment]
i have fixed that in my another PR where i added the scroll bar

**Comment by sreechand2002** [comment]
Once you merge both it will fine

**Comment by srujandeshpande** [comment]
!bounty 5 Fixed in #36

**Pull request closed without merging**
