### PR TITLE
Closes #13

### LINKED ISSUE #13: [ENHANCEMENT] Show Issuing Bank/Service of Credit Card (i.e. Visa, Mastercard, etc)
**Is your feature request related to a problem? Please describe.**
Not really a problem, but an enhancement. This would be a useful real-life application.

**Describe the solution you'd like**
The application should tell you if the card is issued by Mastercard, Visa, or American Express. I'd like to implement regex-based validation for each of these, as per these rules - 

>Actually, that’s a bit of an exaggeration, because credit card numbers actually have some structure to them. All American Express numbers start with 34 or 37; most MasterCard numbers start with 51, 52, 53, 54, or 55 (they also have some other potential starting numbers which we won’t concern ourselves with for this problem); and all Visa numbers start with 4.

_taken from [CS50x](https://cs50.harvard.edu/college/2020/fall/psets/1/credit/)_

**Describe alternatives you've considered**
One could make a request to the various BIN/IIN APIs (for example, [this one](https://binlist.net/))

**Additional context**
no addtional context.

### PR DESCRIPTION
**Pull request by anirudhRowjee**
Hi,

**Brief Description of Fix**
This commit will fix #13 (enhancement).

Changelog -
1. Added regex validators and a function to validate a credit card
   number
2. Modified Luhn's Algorithm function to accept a number as a parameter,
   and then verify the number to return a boolean value
3. Added another function `verify_number` to wrap both of these
   functions, and reflect the changes on the page to the user instead of
   just `console.log()`-ing it.

### CODE REVIEW

**Comment by arjunvuppala123** [comment]
heyy you gotta correct your Js code. There seems to be an error at line 44 in your javascript file. Cause its isnt working

**Comment by anirudhRowjee** [comment]
Could you point out the specific file and line please?

**Review by srujandeshpande — APPROVED** [review]
Looks good and works

**Review by srujandeshpande — APPROVED** [review]

**Comment by srujandeshpande** [comment]
!bounty 50

**Pull request merged**
