### PR TITLE
Fixed Open Issue #44

### LINKED ISSUE #44: Add more types of Cards to the "Type" field
**Is your feature request related to a problem? Please describe.**
Currently, only Mastercard, Visa and AMEX card types are returned by the code when verifying the number

**Describe the solution you'd like**
Add support for more card types (Ex: Discover, JCB, etc)

### PR DESCRIPTION
**Pull request by DivyanshVinayak23**
**Brief Description of Fix**
Added Rupay & Union Pay Regex , Also Fixed Dinners Club Regex 
**Linked Issue**  
Closes #44

### CODE REVIEW

**Comment by ArnavKumar7** [comment]
i would need the source of the regex you have give and also check their validity once , thank you

**Comment by DivyanshVinayak23** [comment]
> i would need the source of the regex you have give and also check their validity once , thank you

https://gist.github.com/michaelkeevildown/9096cd3aac9029c4e6e05588448a8841

**Comment by DivyanshVinayak23** [comment]
@ArnavKumar7 @NavinShrinivas  Please Check

**Comment by anirudhRowjee** [comment]
!bounty 25

**Pull request merged**
